#!/bin/sh
THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
. "$THIS_SCRIPT_DIR/../scripts/test-utilities";

$COMPOSE_ENGINE build;
./user-mirror $COMPOSE_ENGINE run --env USER_MIRROR_CHOWN_LIST=/mnt/volumes/volume/ --volume /mnt/volumes/volume/ --rm sh -c '\
    [ "$(stat -c %u:%g /mnt/volumes/volume/)" = "$(id -u):$(id -g)" ] || \
    (echo "Permissions for /mnt/volumes/volume/ ($(stat -c %u:%g /mnt/volumes/volume/)) != UID:GID ($(id -u):$(id -g))" >&2 && false) \
    ';