#!/bin/sh
THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
. "$THIS_SCRIPT_DIR/../scripts/test-utilities";

$COMPOSE_ENGINE build;
if ! ./user-mirror $COMPOSE_ENGINE run --rm sh -c 'true'; then
    printf 'Expected zero exit code, got a non-zero exit code.\n' >&2;
    exit 1;
fi