#!/bin/sh
THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";
. "$THIS_SCRIPT_DIR/../test-utilities";

eval "$(container_build)";
eval "$(container_run) sh -c 'touch file'";

# Test file exists
if ! [ -e file ]; then
    printf 'file "%s" not found\n' 'file' >&2;
    exit 1;
fi

# Test file ownership matches the current user
file_owner_uid=$(stat -c "%u" file);
file_owner_gid=$(stat -c "%g" file);
user_uid=$(id -u);
user_gid=$(id -g);
if ! [ $file_owner_uid -eq $user_uid ]; then
    printf 'Ownership UID for "file" does not match (expected %s, got %s)\n' $user_uid $file_owner_uid >&2;
    exit 1;
fi
if ! [ $file_owner_gid -eq $user_gid ]; then
    printf 'Ownership GID for "file" does not match (expected %s, got %s)\n' $user_gid $file_owner_gid >&2;
    exit 1;
fi