#!/bin/sh
THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)"
. "$THIS_SCRIPT_DIR/../scripts/test-utilities"

mv compose.yml compose1.yml
cat <<EOF > compose2.yml
services:
  sh:
    volumes:
      - type: volume
        source: volume
        target: /mnt/volumes/volume/
volumes:
  volume:
EOF

$COMPOSE_ENGINE -f compose1.yml -f compose2.yml config > compose.yml
rm compose1.yml
rm compose2.yml

$COMPOSE_ENGINE build
./user-mirror $COMPOSE_ENGINE run --rm sh -c '\
    [ "$(stat -c %u:%g /mnt/volumes/volume/)" = "$(id -u):$(id -g)" ] || \
    (echo "Permissions for /mnt/volumes/volume/ ($(stat -c %u:%g /mnt/volumes/volume/)) != UID:GID ($(id -u):$(id -g))" >&2 && false) \
    '