changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Added Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
  exclude:
    authors:
      - dependabot