#!/bin/sh
set -eC;

THIS_SCRIPT_DIR="$(dirname "$0" | xargs realpath)";

if command -v shellcheck >/dev/null; then
    (cd "$THIS_SCRIPT_DIR" && \
    grep -e '^#!/bin/sh' --exclude-dir=.git -lR | xargs shellcheck --shell=sh --severity=warning && \
    echo 'Shellcheck passed!');
fi

if [ -z "$COMPOSE_ENGINE" ]; then
    (cd "$THIS_SCRIPT_DIR" && ./scripts/matrix-compose-engine scripts/matrix-images scripts/matrix-test-suite scripts/run-test);
else
    (cd "$THIS_SCRIPT_DIR" && COMPOSE_ENGINE="$COMPOSE_ENGINE" ./scripts/matrix-images scripts/matrix-test-suite scripts/run-test);
fi && (echo 'All test pass!' || (echo 'Test failure.' >&2 && false));