#!/bin/sh
set -epC;

SCRIPT_PATH="$(realpath "$1")";
shift;

if docker compose version >/dev/null 2>&1; then
    COMPOSE_ENGINE="docker compose" $SCRIPT_PATH "$@";
elif docker-compose version >/dev/null 2>&1; then
    COMPOSE_ENGINE="docker-compose" $SCRIPT_PATH "$@";
fi

if podman compose version >/dev/null 2>&1; then
    COMPOSE_ENGINE="podman compose" $SCRIPT_PATH "$@";
elif podman-compose version >/dev/null 2>&1; then
    COMPOSE_ENGINE="podman-compose" $SCRIPT_PATH "$@";
fi