#!/bin/sh
set -epC;

SCRIPT_PATH="$(realpath "$1")";
shift;

container_engines() {
    if docker compose version >/dev/null; then
        printf 'docker ';
    fi
    if podman compose version >/dev/null; then
        printf 'podman ';
    fi
}

for container_engine in $(container_engines); do
    CONTAINER_ENGINE="$container_engine" $SCRIPT_PATH $@;
done