#!/bin/sh
set -epC;

container_build() {
    echo "$COMPOSE_ENGINE" build;
}

container_run_args() {
    case "$COMPOSE_ENGINE" in
        docker*) args_script='./docker-user-mirror-args' ;;
        podman*) args_script='./podman-user-mirror-args' ;;
        *) echo >&2 "error: unknown/unsupported compose engine '$COMPOSE_ENGINE'"; exit 1 ;;
    esac

    echo "$(. "$args_script")";
}

container_run() {
    echo "$COMPOSE_ENGINE" run $(container_run_args) --rm;
}