#!/bin/sh
set -eC;

container_build() {
    echo "$COMPOSE_ENGINE" build;
}

container_run_args() {
    case "$COMPOSE_ENGINE" in
        docker*) ./docker-user-mirror-args ;;
        podman*) ./podman-user-mirror-args ;;
        *) printf 'Unknown/unsupported compose engine "%s"\n' "$COMPOSE_ENGINE" >&2; exit 1 ;;
    esac
}

container_run_args >/dev/null;

container_run() {
    echo "$COMPOSE_ENGINE" run "$(container_run_args)" --rm;
}