#!/bin/sh
set -eC;

if docker info -f '{{println .SecurityOptions}}' | grep 'rootless' 1>/dev/null; then
    printf -- '--env GID=%s ' '0';
    printf -- '--env GROUP=%s ' 'root';
    printf -- '--env UID=%s ' '0';
    printf -- '--env USER=%s ' 'root';
else
    printf -- '--env GID=%s ' "$(id -g)";
    printf -- '--env GROUP=%s ' "$(id -gn)";
    printf -- '--env UID=%s ' "$(id -u)";
    printf -- '--env USER=%s ' "$(id -un)";
fi