#!/bin/sh
set -eC;

if docker info -f '{{println .SecurityOptions}}' | grep 'rootless' 1>/dev/null; then
    echo -n --env 'GID=0' '';
    echo -n --env 'GROUP=root' '';
    echo -n --env 'UID=0' '';
    echo -n --env 'USER=root' '';
else
    echo -n --env "GID=$(id -g)" '';
    echo -n --env "GROUP=$(id -gn)" '';
    echo -n --env "UID=$(id -u)" '';
    echo -n --env "USER=$(id -un)" '';
fi